# This file was generated by GoReleaser. DO NOT EDIT.
cask "docsgpt-cli" do
  version "1.6.1"

  on_macos do
    on_arm do
      sha256 "23abde72752a29a351b82dfdba1bf6263add83e301742bf5ade4f10a62eb1cff"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "17ae50cb24b9bed23c9d53655586f399e0552bf9ec0f53d163425813d53d65c6"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "69555294fb45af26618ba9698b40a4a2947e41699b160e4f53b5f42dd97487f0"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e0712ede5e0ea7bf5877ba4c6c815e18fef4e9ca5c0fba2da2c16663895ad97c"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_linux_amd64.tar.gz"
    end
  end

  name "docsgpt-cli"
  desc "Command-line client for DocsGPT agents"
  homepage "https://github.com/arc53/DocsGPT-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docsgpt-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docsgpt-cli"]
    end
  end

  # No zap stanza required
end
