# This file was generated by GoReleaser. DO NOT EDIT.
cask "docsgpt-cli" do
  version "1.9.0"

  on_macos do
    on_arm do
      sha256 "7834757928d83c59a8f35cf7ab6b74ca94cfdc73470f97a6b99240c4538bd10e"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "daded96dce2c96dbb93fdf4fb597215c0b9c9ecf59692f317fa040ae11e7677d"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e486fe131609e4936433a11f465a371e695ddcc517211c71a64ba9fe7b5fffa6"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ea5fd7c40ef26e379fb9fe62fef97917e1f7770ff4ecda93f47017623ac16d9c"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_linux_amd64.tar.gz"
    end
  end

  name "docsgpt-cli"
  desc "Command-line client for DocsGPT agents"
  homepage "https://github.com/arc53/DocsGPT-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docsgpt-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docsgpt-cli"]
    end
  end

  # No zap stanza required
end
