# This file was generated by GoReleaser. DO NOT EDIT.
cask "docsgpt-cli" do
  version "1.6.0"

  on_macos do
    on_arm do
      sha256 "b05a007879e2412d24ebf4b2aec9d96ec7de2b67934d8102cbacbe33f8d348a3"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0944082277f263d1e236f48498ee056c86a382d66c1e19cdccbbc055e48e958b"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d693f915269bd0deebb162dc8a1430ddb822c0f44150dc3b5f2a2a486a252fe0"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0fb32cf1873a0e024e0aa76314602c2c788452030c972e9c2c6577b72679793c"
      url "https://github.com/arc53/DocsGPT-cli/releases/download/v#{version}/docsgpt-cli_linux_amd64.tar.gz"
    end
  end

  name "docsgpt-cli"
  desc "Command-line client for DocsGPT agents"
  homepage "https://github.com/arc53/DocsGPT-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docsgpt-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docsgpt-cli"]
    end
  end

  # No zap stanza required
end
